LedDriver_TunrOn() function is declared
No implementation is done for it, so we have a link-time error:

LedDriverTest.cpp:(.text+0x1c1): undefined reference to `LedDriver_TurnOn'
collect2: error: ld returned 1 exit status